language: node_js
node_js:
  - "8"
sudo: required

services:
- docker

script:
  - npm run coverage
  - npm run startBridge & npm run startE2e
  - cd e2e-script && ./run-tests.sh
after_script:
  - npm run coveralls
