version: '3'
services:
  parity1:
    build: parity
    ports:
      - "8541:8545"
  parity2:
    build: parity
    ports:
      - "8542:8545"
  contracts:
    build: contracts
    command: "true"
  redis:
    image: "redis"
  rabbit:
    image: "rabbitmq:3-management"
    ports:
    - "15672:15672"
  bridge:
    build: bridge
    environment:
    - NODE_ENV=production
    - QUEUE_URL=amqp://rabbit
    - REDIS_URL=redis://redis
    - HOME_RPC_URL=http://parity1:8545
    - FOREIGN_RPC_URL=http://parity2:8545
    - HOME_BRIDGE_ADDRESS=0x32198D570fffC7033641F8A9094FFDCaAEF42624
    - FOREIGN_BRIDGE_ADDRESS=0x2B6871b9B02F73fa24F4864322CdC78604207769
    - ERC20_TOKEN_ADDRESS=0xdbeE25CbE97e4A5CC6c499875774dc7067E9426B
    - VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
    - VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
    - REDIS_LOCK_TTL=1000
    - GAS_PRICE_SPEED_TYPE=standard
    - GAS_PRICE_FALLBACK=1
    - HOME_POLLING_INTERVAL=500
    - FOREIGN_POLLING_INTERVAL=500
    - ALLOW_HTTP=yes
    command: "true"
