version: '3'
services:
  parity1:
    build: parity
    networks:
      testnet:
        ipv4_address: 10.1.0.102
    ports:
    - "8541:8545"
  parity2:
    build: parity
    networks:
      testnet:
        ipv4_address: 10.1.0.103
    ports:
    - "8542:8545"
  contracts:
    build: contracts
    networks:
    - testnet
    command: "true"
  redis:
    image: "redis"
    networks:
    - testnet
  rabbit:
    image: "rabbitmq:3-management"
    networks:
    - testnet
    ports:
    - "15672:15672"
  bridge:
    build: bridge
    environment:
    - NODE_ENV=production
    - QUEUE_URL=amqp://rabbit
    - REDIS_URL=redis://redis
    - HOME_RPC_URL=http://parity1:8545
    - FOREIGN_RPC_URL=http://parity2:8545
    - HOME_BRIDGE_ADDRESS=0x32198D570fffC7033641F8A9094FFDCaAEF42624
    - FOREIGN_BRIDGE_ADDRESS=0x2B6871b9B02F73fa24F4864322CdC78604207769
    - ERC20_TOKEN_ADDRESS=0xdbeE25CbE97e4A5CC6c499875774dc7067E9426B
    - VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
    - VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
    - REDIS_LOCK_TTL=1000
    - GAS_PRICE_SPEED_TYPE=standard
    - GAS_PRICE_FALLBACK=1
    - HOME_POLLING_INTERVAL=500
    - FOREIGN_POLLING_INTERVAL=500
    - ALLOW_HTTP=yes
    networks:
    - testnet
    command: "true"
  selenium-hub:
    image: selenium/hub
    networks:
    - testnet
    ports:
    - "4444:4444"
  chromenode:
    image: selenium/node-chrome
    environment:
    - HUB_PORT_4444_TCP_ADDR=selenium-hub
    - HUB_PORT_4444_TCP_PORT=4444
    networks:
    - testnet
  ui:
    build: ..
    environment:
    - REACT_APP_HOME_BRIDGE_ADDRESS=0x32198D570fffC7033641F8A9094FFDCaAEF42624
    - REACT_APP_FOREIGN_BRIDGE_ADDRESS=0x2B6871b9B02F73fa24F4864322CdC78604207769
    - REACT_APP_FOREIGN_HTTP_PARITY_URL=http://10.1.0.103:8545
    - REACT_APP_HOME_HTTP_PARITY_URL=http://10.1.0.102:8545
    - REACT_APP_GAS_PRICE_SPEED_TYPE=fast
    ports:
    - "3000:3000"
    networks:
      testnet:
        ipv4_address: 10.1.0.101
    command: "true"
  e2e:
    build: ..
    networks:
    - testnet
    command: "true"
networks:
  testnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/24
